// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NetMessages/Control.proto

package NetMessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetPacketType int32

const (
	NetPacket_PING             NetPacketType = 0
	NetPacket_PONG             NetPacketType = 1
	NetPacket_FINDNEIGHBOURREQ NetPacketType = 2
	NetPacket_NEIGHBOUR        NetPacketType = 3
)

var NetPacketType_name = map[int32]string{
	0: "PING",
	1: "PONG",
	2: "FINDNEIGHBOURREQ",
	3: "NEIGHBOUR",
}

var NetPacketType_value = map[string]int32{
	"PING":             0,
	"PONG":             1,
	"FINDNEIGHBOURREQ": 2,
	"NEIGHBOUR":        3,
}

func (x NetPacketType) String() string {
	return proto.EnumName(NetPacketType_name, int32(x))
}

func (NetPacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{0, 0}
}

type NetPacket struct {
	PacketType NetPacketType        `protobuf:"varint,1,opt,name=packet_type,json=packetType,proto3,enum=NetMessages.NetPacketType" json:"packet_type,omitempty"`
	Timestamp  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version    []byte               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Id         []byte               `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Gossip     bool                 `protobuf:"varint,9,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId     []byte               `protobuf:"bytes,10,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodePubKey []byte               `protobuf:"bytes,11,opt,name=node_pub_key,json=nodePubKey,proto3" json:"node_pub_key,omitempty"`
	Sign       []byte               `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*NetPacket_PingData
	//	*NetPacket_PongData
	//	*NetPacket_FindNeighbourReqData
	//	*NetPacket_NeighbourData
	Data                 isNetPacket_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NetPacket) Reset()         { *m = NetPacket{} }
func (m *NetPacket) String() string { return proto.CompactTextString(m) }
func (*NetPacket) ProtoMessage()    {}
func (*NetPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{0}
}

func (m *NetPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetPacket.Unmarshal(m, b)
}
func (m *NetPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetPacket.Marshal(b, m, deterministic)
}
func (m *NetPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetPacket.Merge(m, src)
}
func (m *NetPacket) XXX_Size() int {
	return xxx_messageInfo_NetPacket.Size(m)
}
func (m *NetPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_NetPacket.DiscardUnknown(m)
}

var xxx_messageInfo_NetPacket proto.InternalMessageInfo

func (m *NetPacket) GetPacketType() NetPacketType {
	if m != nil {
		return m.PacketType
	}
	return NetPacket_PING
}

func (m *NetPacket) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NetPacket) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *NetPacket) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *NetPacket) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *NetPacket) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *NetPacket) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *NetPacket) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type isNetPacket_Data interface {
	isNetPacket_Data()
}

type NetPacket_PingData struct {
	PingData *Ping `protobuf:"bytes,4,opt,name=ping_data,json=pingData,proto3,oneof"`
}

type NetPacket_PongData struct {
	PongData *Pong `protobuf:"bytes,5,opt,name=pong_data,json=pongData,proto3,oneof"`
}

type NetPacket_FindNeighbourReqData struct {
	FindNeighbourReqData *FindNeighbourReq `protobuf:"bytes,6,opt,name=find_neighbour_req_data,json=findNeighbourReqData,proto3,oneof"`
}

type NetPacket_NeighbourData struct {
	NeighbourData *Neighbours `protobuf:"bytes,7,opt,name=neighbour_data,json=neighbourData,proto3,oneof"`
}

func (*NetPacket_PingData) isNetPacket_Data() {}

func (*NetPacket_PongData) isNetPacket_Data() {}

func (*NetPacket_FindNeighbourReqData) isNetPacket_Data() {}

func (*NetPacket_NeighbourData) isNetPacket_Data() {}

func (m *NetPacket) GetData() isNetPacket_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NetPacket) GetPingData() *Ping {
	if x, ok := m.GetData().(*NetPacket_PingData); ok {
		return x.PingData
	}
	return nil
}

func (m *NetPacket) GetPongData() *Pong {
	if x, ok := m.GetData().(*NetPacket_PongData); ok {
		return x.PongData
	}
	return nil
}

func (m *NetPacket) GetFindNeighbourReqData() *FindNeighbourReq {
	if x, ok := m.GetData().(*NetPacket_FindNeighbourReqData); ok {
		return x.FindNeighbourReqData
	}
	return nil
}

func (m *NetPacket) GetNeighbourData() *Neighbours {
	if x, ok := m.GetData().(*NetPacket_NeighbourData); ok {
		return x.NeighbourData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NetPacket) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NetPacket_OneofMarshaler, _NetPacket_OneofUnmarshaler, _NetPacket_OneofSizer, []interface{}{
		(*NetPacket_PingData)(nil),
		(*NetPacket_PongData)(nil),
		(*NetPacket_FindNeighbourReqData)(nil),
		(*NetPacket_NeighbourData)(nil),
	}
}

func _NetPacket_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NetPacket)
	// data
	switch x := m.Data.(type) {
	case *NetPacket_PingData:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingData); err != nil {
			return err
		}
	case *NetPacket_PongData:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PongData); err != nil {
			return err
		}
	case *NetPacket_FindNeighbourReqData:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FindNeighbourReqData); err != nil {
			return err
		}
	case *NetPacket_NeighbourData:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NeighbourData); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NetPacket.Data has unexpected type %T", x)
	}
	return nil
}

func _NetPacket_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NetPacket)
	switch tag {
	case 4: // data.ping_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ping)
		err := b.DecodeMessage(msg)
		m.Data = &NetPacket_PingData{msg}
		return true, err
	case 5: // data.pong_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Pong)
		err := b.DecodeMessage(msg)
		m.Data = &NetPacket_PongData{msg}
		return true, err
	case 6: // data.find_neighbour_req_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FindNeighbourReq)
		err := b.DecodeMessage(msg)
		m.Data = &NetPacket_FindNeighbourReqData{msg}
		return true, err
	case 7: // data.neighbour_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Neighbours)
		err := b.DecodeMessage(msg)
		m.Data = &NetPacket_NeighbourData{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NetPacket_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NetPacket)
	// data
	switch x := m.Data.(type) {
	case *NetPacket_PingData:
		s := proto.Size(x.PingData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NetPacket_PongData:
		s := proto.Size(x.PongData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NetPacket_FindNeighbourReqData:
		s := proto.Size(x.FindNeighbourReqData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NetPacket_NeighbourData:
		s := proto.Size(x.NeighbourData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Ping struct {
	To                   []byte   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type Pong struct {
	To                   []byte   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	ReplyTok             []byte   `protobuf:"bytes,2,opt,name=reply_tok,json=replyTok,proto3" json:"reply_tok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{2}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Pong) GetReplyTok() []byte {
	if m != nil {
		return m.ReplyTok
	}
	return nil
}

type FindNeighbourReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNeighbourReq) Reset()         { *m = FindNeighbourReq{} }
func (m *FindNeighbourReq) String() string { return proto.CompactTextString(m) }
func (*FindNeighbourReq) ProtoMessage()    {}
func (*FindNeighbourReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{3}
}

func (m *FindNeighbourReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNeighbourReq.Unmarshal(m, b)
}
func (m *FindNeighbourReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNeighbourReq.Marshal(b, m, deterministic)
}
func (m *FindNeighbourReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNeighbourReq.Merge(m, src)
}
func (m *FindNeighbourReq) XXX_Size() int {
	return xxx_messageInfo_FindNeighbourReq.Size(m)
}
func (m *FindNeighbourReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNeighbourReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindNeighbourReq proto.InternalMessageInfo

type Neighbours struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Neighbours) Reset()         { *m = Neighbours{} }
func (m *Neighbours) String() string { return proto.CompactTextString(m) }
func (*Neighbours) ProtoMessage()    {}
func (*Neighbours) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{4}
}

func (m *Neighbours) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Neighbours.Unmarshal(m, b)
}
func (m *Neighbours) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Neighbours.Marshal(b, m, deterministic)
}
func (m *Neighbours) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neighbours.Merge(m, src)
}
func (m *Neighbours) XXX_Size() int {
	return xxx_messageInfo_Neighbours.Size(m)
}
func (m *Neighbours) XXX_DiscardUnknown() {
	xxx_messageInfo_Neighbours.DiscardUnknown(m)
}

var xxx_messageInfo_Neighbours proto.InternalMessageInfo

func (m *Neighbours) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Node                 []byte   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ad738315f2b2f5, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterEnum("NetMessages.NetPacketType", NetPacketType_name, NetPacketType_value)
	proto.RegisterType((*NetPacket)(nil), "NetMessages.net_packet")
	proto.RegisterType((*Ping)(nil), "NetMessages.ping")
	proto.RegisterType((*Pong)(nil), "NetMessages.pong")
	proto.RegisterType((*FindNeighbourReq)(nil), "NetMessages.find_neighbour_req")
	proto.RegisterType((*Neighbours)(nil), "NetMessages.neighbours")
	proto.RegisterType((*Node)(nil), "NetMessages.node")
}

func init() { proto.RegisterFile("NetMessages/Control.proto", fileDescriptor_74ad738315f2b2f5) }

var fileDescriptor_74ad738315f2b2f5 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x6f, 0xba, 0xac, 0x4d, 0xae, 0x59, 0x15, 0xac, 0x6a, 0x35, 0x05, 0x69, 0x51, 0x5e, 0xe8,
	0x53, 0x8a, 0x36, 0x21, 0xf1, 0x82, 0x40, 0x63, 0xa3, 0xad, 0x10, 0xd9, 0xb0, 0x8a, 0xc4, 0x5b,
	0x94, 0x10, 0x2f, 0x58, 0xed, 0xe2, 0x2c, 0x76, 0x91, 0xf2, 0x69, 0xf9, 0x2a, 0xc8, 0x4e, 0xd2,
	0x6e, 0x2b, 0x4f, 0xbe, 0xfb, 0xfd, 0x39, 0xdb, 0x77, 0x07, 0x2f, 0x43, 0x2a, 0xbf, 0x51, 0x21,
	0xe2, 0x8c, 0x8a, 0xd9, 0x67, 0x9e, 0xcb, 0x92, 0x6f, 0x82, 0xa2, 0xe4, 0x92, 0xa3, 0xc1, 0x23,
	0x6a, 0x72, 0x96, 0x71, 0x9e, 0x6d, 0xe8, 0x4c, 0x53, 0xc9, 0xf6, 0x6e, 0x26, 0xd9, 0x3d, 0x15,
	0x32, 0xbe, 0x2f, 0x6a, 0xb5, 0xff, 0xd7, 0x04, 0xc8, 0xa9, 0x8c, 0x8a, 0xf8, 0xd7, 0x9a, 0x4a,
	0xf4, 0x01, 0x06, 0x75, 0x14, 0xc9, 0xaa, 0xa0, 0xd8, 0xf0, 0x8c, 0xe9, 0xf0, 0xfc, 0x75, 0xf0,
	0xa8, 0x64, 0xb0, 0x57, 0x07, 0x4a, 0x43, 0xa0, 0x4e, 0x56, 0x55, 0x41, 0xd1, 0x7b, 0xb0, 0x77,
	0x17, 0xe0, 0xae, 0x67, 0x4c, 0x07, 0xe7, 0x93, 0xa0, 0x7e, 0x42, 0xd0, 0x3e, 0x21, 0x58, 0xb5,
	0x0a, 0xb2, 0x17, 0x23, 0x0c, 0xfd, 0x3f, 0xb4, 0x14, 0x8c, 0xe7, 0xf8, 0xc8, 0x33, 0xa6, 0x0e,
	0x69, 0x53, 0x34, 0x84, 0x2e, 0x4b, 0xb1, 0xa5, 0xc1, 0x2e, 0x4b, 0xd1, 0x29, 0xf4, 0x32, 0x2e,
	0x04, 0x2b, 0xb0, 0xed, 0x19, 0x53, 0x8b, 0x34, 0x19, 0x1a, 0x43, 0x3f, 0xe7, 0x29, 0x8d, 0x58,
	0x8a, 0x41, 0x8b, 0x7b, 0x2a, 0x5d, 0xa6, 0xc8, 0x03, 0x47, 0x13, 0xc5, 0x36, 0x89, 0xd6, 0xb4,
	0xc2, 0x03, 0xcd, 0x82, 0xc2, 0x6e, 0xb7, 0xc9, 0x57, 0x5a, 0x21, 0x04, 0xa6, 0x60, 0x59, 0x8e,
	0x1d, 0xcd, 0xe8, 0x18, 0xbd, 0x05, 0xbb, 0x60, 0x79, 0x16, 0xa5, 0xb1, 0x8c, 0xb1, 0xa9, 0xbf,
	0xf2, 0xe2, 0x49, 0x1f, 0x14, 0xbb, 0xe8, 0x10, 0x4b, 0x9d, 0x57, 0xb1, 0x8c, 0xb5, 0x83, 0xb7,
	0x8e, 0xe3, 0xff, 0x39, 0x78, 0xe3, 0xe0, 0x8d, 0xe3, 0x27, 0x8c, 0xef, 0x58, 0x9e, 0x46, 0x39,
	0x65, 0xd9, 0xef, 0x84, 0x6f, 0xcb, 0xa8, 0xa4, 0x0f, 0xb5, 0xbf, 0xa7, 0xfd, 0x67, 0x4f, 0xfc,
	0x87, 0xda, 0x45, 0x87, 0x8c, 0x14, 0x1a, 0xb6, 0x20, 0xa1, 0x0f, 0xba, 0xf2, 0x27, 0x18, 0xee,
	0x85, 0xba, 0x60, 0x5f, 0x17, 0x1c, 0x3f, 0x1b, 0x65, 0x23, 0x11, 0x8b, 0x0e, 0x39, 0xd9, 0x65,
	0xaa, 0x82, 0xff, 0x11, 0x4c, 0x35, 0x5e, 0x64, 0x81, 0x79, 0xbb, 0x0c, 0xe7, 0x6e, 0x47, 0x47,
	0x37, 0xe1, 0xdc, 0x35, 0xd0, 0x08, 0xdc, 0x2f, 0xcb, 0xf0, 0x2a, 0xbc, 0x5e, 0xce, 0x17, 0x97,
	0x37, 0x3f, 0x08, 0xb9, 0xfe, 0xee, 0x76, 0xd1, 0x09, 0xd8, 0x3b, 0xc4, 0x3d, 0xba, 0xec, 0x81,
	0xa9, 0x2e, 0xf6, 0x4f, 0xc1, 0x54, 0x2d, 0x52, 0x73, 0x94, 0x5c, 0x6f, 0x94, 0x43, 0xba, 0x92,
	0xfb, 0x17, 0x60, 0xaa, 0x46, 0x3c, 0xc7, 0xd1, 0x2b, 0xb0, 0x4b, 0x5a, 0x6c, 0xaa, 0x48, 0xf2,
	0xb5, 0xde, 0x21, 0x87, 0x58, 0x1a, 0x58, 0xf1, 0xb5, 0x3f, 0x02, 0x74, 0xd8, 0x05, 0xff, 0x9d,
	0xda, 0xe1, 0xf6, 0x2b, 0xe8, 0x0d, 0x1c, 0xab, 0xd9, 0x0a, 0x6c, 0x78, 0x47, 0x07, 0x33, 0x50,
	0x0c, 0xa9, 0x79, 0x7f, 0x02, 0xa6, 0x0a, 0xd4, 0xf8, 0xd5, 0xd9, 0xbc, 0x41, 0xc7, 0x49, 0x4f,
	0xaf, 0xeb, 0xc5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x4c, 0xb7, 0xa8, 0x69, 0x03, 0x00,
	0x00,
}
