// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Messages/Messages.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PacketType int32

const (
	Packet_BUNDLE      PacketType = 0
	Packet_BLOCK       PacketType = 1
	Packet_REP         PacketType = 2
	Packet_WEAKREQ     PacketType = 3
	Packet_SANITYCHECK PacketType = 4
)

var PacketType_name = map[int32]string{
	0: "BUNDLE",
	1: "BLOCK",
	2: "REP",
	3: "WEAKREQ",
	4: "SANITYCHECK",
}

var PacketType_value = map[string]int32{
	"BUNDLE":      0,
	"BLOCK":       1,
	"REP":         2,
	"WEAKREQ":     3,
	"SANITYCHECK": 4,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{0, 0}
}

type BundleType int32

const (
	Bundle_POWERFUL BundleType = 0
	Bundle_WEAK     BundleType = 1
)

var BundleType_name = map[int32]string{
	0: "POWERFUL",
	1: "WEAK",
}

var BundleType_value = map[string]int32{
	"POWERFUL": 0,
	"WEAK":     1,
}

func (x BundleType) String() string {
	return proto.EnumName(BundleType_name, int32(x))
}

func (BundleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{3, 0}
}

type RepType int32

const (
	Rep_POPR    RepType = 0
	Rep_POPRA   RepType = 1
	Rep_REVIEW  RepType = 2
	Rep_INITIAL RepType = 3
)

var RepType_name = map[int32]string{
	0: "POPR",
	1: "POPRA",
	2: "REVIEW",
	3: "INITIAL",
}

var RepType_value = map[string]int32{
	"POPR":    0,
	"POPRA":   1,
	"REVIEW":  2,
	"INITIAL": 3,
}

func (x RepType) String() string {
	return proto.EnumName(RepType_name, int32(x))
}

func (RepType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{6, 0}
}

type Packet struct {
	PacketType         PacketType           `protobuf:"varint,1,opt,name=packet_type,json=packetType,proto3,enum=msg.PacketType" json:"packet_type,omitempty"`
	Timestamp          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Prev               []byte               `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Nonce              []byte               `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Diff               uint32               `protobuf:"varint,5,opt,name=diff,proto3" json:"diff,omitempty"`
	Hash               []byte               `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	CurrentBlockNumber uint64               `protobuf:"varint,7,opt,name=current_block_number,json=currentBlockNumber,proto3" json:"current_block_number,omitempty"`
	Addr               []byte               `protobuf:"bytes,13,opt,name=addr,proto3" json:"addr,omitempty"`
	Sign               []byte               `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Packet_BlockData
	//	*Packet_BundleData
	//	*Packet_RepData
	//	*Packet_WeakData
	//	*Packet_SanityData
	Data                 isPacket_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetPacketType() PacketType {
	if m != nil {
		return m.PacketType
	}
	return Packet_BUNDLE
}

func (m *Packet) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Packet) GetPrev() []byte {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *Packet) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Packet) GetDiff() uint32 {
	if m != nil {
		return m.Diff
	}
	return 0
}

func (m *Packet) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Packet) GetCurrentBlockNumber() uint64 {
	if m != nil {
		return m.CurrentBlockNumber
	}
	return 0
}

func (m *Packet) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Packet) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type isPacket_Data interface {
	isPacket_Data()
}

type Packet_BlockData struct {
	BlockData *Block `protobuf:"bytes,8,opt,name=blockData,proto3,oneof"`
}

type Packet_BundleData struct {
	BundleData *Bundle `protobuf:"bytes,9,opt,name=bundleData,proto3,oneof"`
}

type Packet_RepData struct {
	RepData *Rep `protobuf:"bytes,10,opt,name=repData,proto3,oneof"`
}

type Packet_WeakData struct {
	WeakData *WeakReq `protobuf:"bytes,11,opt,name=weakData,proto3,oneof"`
}

type Packet_SanityData struct {
	SanityData *SanityCheck `protobuf:"bytes,12,opt,name=sanityData,proto3,oneof"`
}

func (*Packet_BlockData) isPacket_Data() {}

func (*Packet_BundleData) isPacket_Data() {}

func (*Packet_RepData) isPacket_Data() {}

func (*Packet_WeakData) isPacket_Data() {}

func (*Packet_SanityData) isPacket_Data() {}

func (m *Packet) GetData() isPacket_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Packet) GetBlockData() *Block {
	if x, ok := m.GetData().(*Packet_BlockData); ok {
		return x.BlockData
	}
	return nil
}

func (m *Packet) GetBundleData() *Bundle {
	if x, ok := m.GetData().(*Packet_BundleData); ok {
		return x.BundleData
	}
	return nil
}

func (m *Packet) GetRepData() *Rep {
	if x, ok := m.GetData().(*Packet_RepData); ok {
		return x.RepData
	}
	return nil
}

func (m *Packet) GetWeakData() *WeakReq {
	if x, ok := m.GetData().(*Packet_WeakData); ok {
		return x.WeakData
	}
	return nil
}

func (m *Packet) GetSanityData() *SanityCheck {
	if x, ok := m.GetData().(*Packet_SanityData); ok {
		return x.SanityData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Packet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Packet_OneofMarshaler, _Packet_OneofUnmarshaler, _Packet_OneofSizer, []interface{}{
		(*Packet_BlockData)(nil),
		(*Packet_BundleData)(nil),
		(*Packet_RepData)(nil),
		(*Packet_WeakData)(nil),
		(*Packet_SanityData)(nil),
	}
}

func _Packet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Packet)
	// data
	switch x := m.Data.(type) {
	case *Packet_BlockData:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BlockData); err != nil {
			return err
		}
	case *Packet_BundleData:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BundleData); err != nil {
			return err
		}
	case *Packet_RepData:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RepData); err != nil {
			return err
		}
	case *Packet_WeakData:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WeakData); err != nil {
			return err
		}
	case *Packet_SanityData:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SanityData); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Packet.Data has unexpected type %T", x)
	}
	return nil
}

func _Packet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Packet)
	switch tag {
	case 8: // data.blockData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Block)
		err := b.DecodeMessage(msg)
		m.Data = &Packet_BlockData{msg}
		return true, err
	case 9: // data.bundleData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Bundle)
		err := b.DecodeMessage(msg)
		m.Data = &Packet_BundleData{msg}
		return true, err
	case 10: // data.repData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Rep)
		err := b.DecodeMessage(msg)
		m.Data = &Packet_RepData{msg}
		return true, err
	case 11: // data.weakData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WeakReq)
		err := b.DecodeMessage(msg)
		m.Data = &Packet_WeakData{msg}
		return true, err
	case 12: // data.sanityData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SanityCheck)
		err := b.DecodeMessage(msg)
		m.Data = &Packet_SanityData{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Packet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Packet)
	// data
	switch x := m.Data.(type) {
	case *Packet_BlockData:
		s := proto.Size(x.BlockData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_BundleData:
		s := proto.Size(x.BundleData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_RepData:
		s := proto.Size(x.RepData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_WeakData:
		s := proto.Size(x.WeakData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Packet_SanityData:
		s := proto.Size(x.SanityData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Block struct {
	Reqs                 []*WeakReq     `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	BundleHashs          []*HashArray   `protobuf:"bytes,2,rep,name=bundleHashs,proto3" json:"bundleHashs,omitempty"`
	Sanities             []*SanityCheck `protobuf:"bytes,3,rep,name=sanities,proto3" json:"sanities,omitempty"`
	Coinbase             *Tx            `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetReqs() []*WeakReq {
	if m != nil {
		return m.Reqs
	}
	return nil
}

func (m *Block) GetBundleHashs() []*HashArray {
	if m != nil {
		return m.BundleHashs
	}
	return nil
}

func (m *Block) GetSanities() []*SanityCheck {
	if m != nil {
		return m.Sanities
	}
	return nil
}

func (m *Block) GetCoinbase() *Tx {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

type HashArray struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashArray) Reset()         { *m = HashArray{} }
func (m *HashArray) String() string { return proto.CompactTextString(m) }
func (*HashArray) ProtoMessage()    {}
func (*HashArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{2}
}

func (m *HashArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashArray.Unmarshal(m, b)
}
func (m *HashArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashArray.Marshal(b, m, deterministic)
}
func (m *HashArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashArray.Merge(m, src)
}
func (m *HashArray) XXX_Size() int {
	return xxx_messageInfo_HashArray.Size(m)
}
func (m *HashArray) XXX_DiscardUnknown() {
	xxx_messageInfo_HashArray.DiscardUnknown(m)
}

var xxx_messageInfo_HashArray proto.InternalMessageInfo

func (m *HashArray) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Bundle struct {
	BundleType           BundleType `protobuf:"varint,1,opt,name=bundle_type,json=bundleType,proto3,enum=msg.BundleType" json:"bundle_type,omitempty"`
	Hash                 []byte     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions         []*Tx      `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Verify1              []byte     `protobuf:"bytes,4,opt,name=verify1,proto3" json:"verify1,omitempty"`
	Verify2              []byte     `protobuf:"bytes,5,opt,name=verify2,proto3" json:"verify2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{3}
}

func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle.Unmarshal(m, b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return xxx_messageInfo_Bundle.Size(m)
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetBundleType() BundleType {
	if m != nil {
		return m.BundleType
	}
	return Bundle_POWERFUL
}

func (m *Bundle) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Bundle) GetTransactions() []*Tx {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Bundle) GetVerify1() []byte {
	if m != nil {
		return m.Verify1
	}
	return nil
}

func (m *Bundle) GetVerify2() []byte {
	if m != nil {
		return m.Verify2
	}
	return nil
}

type Tx struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BundleHash           []byte   `protobuf:"bytes,6,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	RefTx                []byte   `protobuf:"bytes,2,opt,name=refTx,proto3" json:"refTx,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Value                int64    `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Tag                  []byte   `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{4}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Tx) GetBundleHash() []byte {
	if m != nil {
		return m.BundleHash
	}
	return nil
}

func (m *Tx) GetRefTx() []byte {
	if m != nil {
		return m.RefTx
	}
	return nil
}

func (m *Tx) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Tx) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Tx) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

type WeakReq struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeakReq) Reset()         { *m = WeakReq{} }
func (m *WeakReq) String() string { return proto.CompactTextString(m) }
func (*WeakReq) ProtoMessage()    {}
func (*WeakReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{5}
}

func (m *WeakReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeakReq.Unmarshal(m, b)
}
func (m *WeakReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeakReq.Marshal(b, m, deterministic)
}
func (m *WeakReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeakReq.Merge(m, src)
}
func (m *WeakReq) XXX_Size() int {
	return xxx_messageInfo_WeakReq.Size(m)
}
func (m *WeakReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WeakReq.DiscardUnknown(m)
}

var xxx_messageInfo_WeakReq proto.InternalMessageInfo

func (m *WeakReq) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *WeakReq) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Rep struct {
	Hash                 RepType  `protobuf:"varint,1,opt,name=hash,proto3,enum=msg.RepType" json:"hash,omitempty"`
	Addr                 []byte   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	RepReview            *Review  `protobuf:"bytes,3,opt,name=rep_review,json=repReview,proto3" json:"rep_review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rep) Reset()         { *m = Rep{} }
func (m *Rep) String() string { return proto.CompactTextString(m) }
func (*Rep) ProtoMessage()    {}
func (*Rep) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{6}
}

func (m *Rep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rep.Unmarshal(m, b)
}
func (m *Rep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rep.Marshal(b, m, deterministic)
}
func (m *Rep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rep.Merge(m, src)
}
func (m *Rep) XXX_Size() int {
	return xxx_messageInfo_Rep.Size(m)
}
func (m *Rep) XXX_DiscardUnknown() {
	xxx_messageInfo_Rep.DiscardUnknown(m)
}

var xxx_messageInfo_Rep proto.InternalMessageInfo

func (m *Rep) GetHash() RepType {
	if m != nil {
		return m.Hash
	}
	return Rep_POPR
}

func (m *Rep) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Rep) GetRepReview() *Review {
	if m != nil {
		return m.RepReview
	}
	return nil
}

type Review struct {
	Rate                 uint32   `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
	Confidence           uint32   `protobuf:"varint,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	IpfsReview           []byte   `protobuf:"bytes,3,opt,name=ipfs_review,json=ipfsReview,proto3" json:"ipfs_review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{7}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Review) GetConfidence() uint32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *Review) GetIpfsReview() []byte {
	if m != nil {
		return m.IpfsReview
	}
	return nil
}

type Initial struct {
	POBurn               *Bundle  `protobuf:"bytes,1,opt,name=p_o_burn,json=pOBurn,proto3" json:"p_o_burn,omitempty"`
	Service              []byte   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	OwnerAddr            []byte   `protobuf:"bytes,3,opt,name=owner_addr,json=ownerAddr,proto3" json:"owner_addr,omitempty"`
	IpfsDetail           []byte   `protobuf:"bytes,4,opt,name=ipfs_detail,json=ipfsDetail,proto3" json:"ipfs_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Initial) Reset()         { *m = Initial{} }
func (m *Initial) String() string { return proto.CompactTextString(m) }
func (*Initial) ProtoMessage()    {}
func (*Initial) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{8}
}

func (m *Initial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Initial.Unmarshal(m, b)
}
func (m *Initial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Initial.Marshal(b, m, deterministic)
}
func (m *Initial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Initial.Merge(m, src)
}
func (m *Initial) XXX_Size() int {
	return xxx_messageInfo_Initial.Size(m)
}
func (m *Initial) XXX_DiscardUnknown() {
	xxx_messageInfo_Initial.DiscardUnknown(m)
}

var xxx_messageInfo_Initial proto.InternalMessageInfo

func (m *Initial) GetPOBurn() *Bundle {
	if m != nil {
		return m.POBurn
	}
	return nil
}

func (m *Initial) GetService() []byte {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Initial) GetOwnerAddr() []byte {
	if m != nil {
		return m.OwnerAddr
	}
	return nil
}

func (m *Initial) GetIpfsDetail() []byte {
	if m != nil {
		return m.IpfsDetail
	}
	return nil
}

type SanityCheck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SanityCheck) Reset()         { *m = SanityCheck{} }
func (m *SanityCheck) String() string { return proto.CompactTextString(m) }
func (*SanityCheck) ProtoMessage()    {}
func (*SanityCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fc5e78786d5f342, []int{9}
}

func (m *SanityCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SanityCheck.Unmarshal(m, b)
}
func (m *SanityCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SanityCheck.Marshal(b, m, deterministic)
}
func (m *SanityCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SanityCheck.Merge(m, src)
}
func (m *SanityCheck) XXX_Size() int {
	return xxx_messageInfo_SanityCheck.Size(m)
}
func (m *SanityCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_SanityCheck.DiscardUnknown(m)
}

var xxx_messageInfo_SanityCheck proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("msg.PacketType", PacketType_name, PacketType_value)
	proto.RegisterEnum("msg.BundleType", BundleType_name, BundleType_value)
	proto.RegisterEnum("msg.RepType", RepType_name, RepType_value)
	proto.RegisterType((*Packet)(nil), "msg.packet")
	proto.RegisterType((*Block)(nil), "msg.block")
	proto.RegisterType((*HashArray)(nil), "msg.HashArray")
	proto.RegisterType((*Bundle)(nil), "msg.bundle")
	proto.RegisterType((*Tx)(nil), "msg.tx")
	proto.RegisterType((*WeakReq)(nil), "msg.weak_req")
	proto.RegisterType((*Rep)(nil), "msg.rep")
	proto.RegisterType((*Review)(nil), "msg.review")
	proto.RegisterType((*Initial)(nil), "msg.initial")
	proto.RegisterType((*SanityCheck)(nil), "msg.sanity_check")
}

func init() { proto.RegisterFile("Messages/Messages.proto", fileDescriptor_3fc5e78786d5f342) }

var fileDescriptor_3fc5e78786d5f342 = []byte{
	// 880 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x15, 0x45, 0xea, 0x36, 0xba, 0x94, 0x5d, 0x18, 0x28, 0x11, 0xa0, 0xb1, 0xca, 0xb6, 0x80,
	0x90, 0x20, 0x72, 0xa2, 0xe4, 0xa1, 0xaf, 0x92, 0xad, 0x42, 0x82, 0x5d, 0xdb, 0xdd, 0x2a, 0x35,
	0xfa, 0x50, 0x10, 0x2b, 0x69, 0x25, 0x13, 0x91, 0x48, 0x66, 0x77, 0x25, 0x5b, 0xbf, 0xd0, 0xfe,
	0x43, 0xbf, 0xa1, 0x9f, 0x52, 0xf4, 0x8b, 0x82, 0x9d, 0x25, 0x29, 0x06, 0xce, 0xdb, 0xcc, 0x99,
	0xa3, 0xb9, 0xed, 0x1c, 0x0a, 0xbe, 0xf9, 0x85, 0x4b, 0xc9, 0xd6, 0x5c, 0x9e, 0x65, 0x46, 0x3f,
	0x11, 0xb1, 0x8a, 0x89, 0xbd, 0x95, 0xeb, 0x67, 0xa7, 0xeb, 0x38, 0x5e, 0x6f, 0xf8, 0x19, 0x42,
	0xf3, 0xdd, 0xea, 0x4c, 0x85, 0x5b, 0x2e, 0x15, 0xdb, 0x26, 0x86, 0xe5, 0xff, 0xef, 0x40, 0x35,
	0x61, 0x8b, 0x0f, 0x5c, 0x91, 0x37, 0xd0, 0x34, 0x56, 0xa0, 0x0e, 0x09, 0xf7, 0xac, 0xae, 0xd5,
	0xeb, 0x0c, 0xdc, 0xfe, 0x56, 0xae, 0xfb, 0x06, 0xef, 0x6b, 0x9c, 0x82, 0x71, 0x66, 0x87, 0x84,
	0x93, 0x9f, 0xa0, 0x91, 0x27, 0xf4, 0xca, 0x5d, 0xab, 0xd7, 0x1c, 0x3c, 0xeb, 0x9b, 0x92, 0xfd,
	0xac, 0x64, 0x7f, 0x96, 0x31, 0xe8, 0x91, 0x4c, 0x08, 0x38, 0x89, 0xe0, 0x7b, 0xcf, 0xee, 0x5a,
	0xbd, 0x16, 0x45, 0x9b, 0x9c, 0x40, 0x25, 0x8a, 0xa3, 0x05, 0xf7, 0x1c, 0x04, 0x8d, 0xa3, 0x99,
	0xcb, 0x70, 0xb5, 0xf2, 0x2a, 0x5d, 0xab, 0xd7, 0xa6, 0x68, 0x6b, 0xec, 0x9e, 0xc9, 0x7b, 0xaf,
	0x6a, 0x7e, 0xad, 0x6d, 0xf2, 0x1a, 0x4e, 0x16, 0x3b, 0x21, 0x78, 0xa4, 0x82, 0xf9, 0x26, 0x5e,
	0x7c, 0x08, 0xa2, 0xdd, 0x76, 0xce, 0x85, 0x57, 0xeb, 0x5a, 0x3d, 0x87, 0x92, 0x34, 0x36, 0xd2,
	0xa1, 0x6b, 0x8c, 0xe8, 0x2c, 0x6c, 0xb9, 0x14, 0x5e, 0xdb, 0x64, 0xd1, 0xb6, 0xc6, 0x64, 0xb8,
	0x8e, 0xbc, 0x8e, 0xc1, 0xb4, 0x4d, 0x5e, 0x40, 0x03, 0x33, 0x5e, 0x30, 0xc5, 0xbc, 0x3a, 0x4e,
	0x09, 0xb8, 0x16, 0x44, 0x27, 0x25, 0x7a, 0x0c, 0x93, 0x57, 0x00, 0xf3, 0x5d, 0xb4, 0xdc, 0x70,
	0x24, 0x37, 0x90, 0xdc, 0x34, 0x64, 0x84, 0x27, 0x25, 0x5a, 0x20, 0x90, 0x1f, 0xa0, 0x26, 0x78,
	0x82, 0x5c, 0x40, 0x6e, 0x1d, 0xb9, 0x82, 0x27, 0x93, 0x12, 0xcd, 0x42, 0xe4, 0x25, 0xd4, 0x1f,
	0x38, 0x33, 0xf5, 0x9b, 0x48, 0x6b, 0x23, 0x4d, 0x83, 0x81, 0xe0, 0x1f, 0x27, 0x25, 0x9a, 0x13,
	0xc8, 0x5b, 0x00, 0xc9, 0xa2, 0x50, 0x1d, 0x90, 0xde, 0x42, 0xfa, 0xd7, 0x48, 0x37, 0x70, 0xb0,
	0xb8, 0xe7, 0xd8, 0x75, 0x81, 0xe6, 0x5f, 0x80, 0xa3, 0x1f, 0x97, 0x00, 0x54, 0x47, 0xef, 0xaf,
	0x2f, 0xae, 0xc6, 0x6e, 0x89, 0x34, 0xa0, 0x32, 0xba, 0xba, 0x39, 0xbf, 0x74, 0x2d, 0x52, 0x03,
	0x9b, 0x8e, 0x6f, 0xdd, 0x32, 0x69, 0x42, 0xed, 0x6e, 0x3c, 0xbc, 0xa4, 0xe3, 0x5f, 0x5d, 0x9b,
	0x7c, 0x05, 0xcd, 0xdf, 0x86, 0xd7, 0xd3, 0xd9, 0x1f, 0xe7, 0x93, 0xf1, 0xf9, 0xa5, 0xeb, 0x8c,
	0xaa, 0xe0, 0x2c, 0x75, 0xb6, 0x7f, 0x2d, 0xa8, 0xe0, 0x4a, 0xc8, 0x77, 0xe0, 0x08, 0xfe, 0x51,
	0x7a, 0x56, 0xd7, 0x7e, 0xd2, 0x35, 0xc5, 0x10, 0x79, 0x0d, 0xcd, 0x74, 0x35, 0x4c, 0xde, 0x4b,
	0xaf, 0x8c, 0xcc, 0x0e, 0x32, 0x35, 0x32, 0x14, 0x82, 0x1d, 0x68, 0x91, 0x42, 0x5e, 0x41, 0x1d,
	0x5b, 0x0f, 0xb9, 0xf4, 0x6c, 0xa4, 0x3f, 0x9d, 0x8f, 0xe6, 0x14, 0xf2, 0x3d, 0xd4, 0x17, 0x71,
	0x18, 0xcd, 0x99, 0x34, 0x97, 0xd5, 0x1c, 0xd4, 0x90, 0xae, 0x1e, 0x69, 0x1e, 0xf0, 0x4f, 0xa1,
	0x91, 0x57, 0xcb, 0xcf, 0xcb, 0x3a, 0x9e, 0x97, 0xff, 0x9f, 0x05, 0x55, 0xd3, 0x84, 0x16, 0x8a,
	0xb1, 0x9e, 0x0a, 0xc5, 0xe0, 0xa9, 0x50, 0x8c, 0x83, 0x42, 0xc9, 0x32, 0x96, 0x0b, 0x07, 0xfb,
	0x12, 0x5a, 0x4a, 0xb0, 0x48, 0xb2, 0x85, 0x0a, 0xe3, 0x28, 0x1b, 0x25, 0xef, 0xed, 0xb3, 0x20,
	0xf1, 0xa0, 0xb6, 0xe7, 0x22, 0x5c, 0x1d, 0xde, 0xa4, 0xea, 0xc8, 0xdc, 0x63, 0x64, 0x80, 0x12,
	0xc9, 0x23, 0x03, 0xff, 0x79, 0xfa, 0xa8, 0x2d, 0xa8, 0xdf, 0xde, 0xdc, 0x8d, 0xe9, 0xcf, 0xef,
	0xaf, 0xdc, 0x12, 0xa9, 0x83, 0xa3, 0x9f, 0xd0, 0xb5, 0xfc, 0xbf, 0x2d, 0x28, 0xab, 0xc7, 0x2f,
	0x4d, 0x4b, 0x4e, 0xf3, 0x11, 0x0b, 0x3a, 0x83, 0xe3, 0x23, 0x68, 0xad, 0x0a, 0xbe, 0x9a, 0x3d,
	0xa6, 0x13, 0x19, 0x27, 0x57, 0x8f, 0x5d, 0x50, 0xcf, 0x09, 0x54, 0xf6, 0x6c, 0xb3, 0x33, 0xbb,
	0xb7, 0xa9, 0x71, 0x88, 0x0b, 0xb6, 0x62, 0xeb, 0xb4, 0x63, 0x6d, 0xfa, 0xef, 0xcc, 0x91, 0xeb,
	0xcb, 0xf8, 0x62, 0x4b, 0x27, 0x50, 0x51, 0xb1, 0x62, 0x1b, 0xac, 0xd8, 0xa6, 0xc6, 0xf1, 0xff,
	0xb1, 0xc0, 0x16, 0x3c, 0xd1, 0x87, 0x96, 0xff, 0xa2, 0x93, 0x1e, 0x9a, 0xe0, 0x89, 0x79, 0x09,
	0x93, 0x20, 0x93, 0x7b, 0xb9, 0x20, 0xf7, 0x17, 0x00, 0x82, 0x27, 0x81, 0xe0, 0xfb, 0x90, 0x3f,
	0x60, 0xdb, 0x99, 0x5c, 0x0d, 0x44, 0x1b, 0x82, 0x27, 0x14, 0x4d, 0xff, 0x5d, 0xba, 0xce, 0x3a,
	0x38, 0xb7, 0x37, 0xb7, 0xd4, 0x28, 0x44, 0x5b, 0x43, 0xd7, 0xd2, 0xc2, 0xa1, 0xe3, 0xdf, 0xa7,
	0xe3, 0x3b, 0x23, 0x92, 0xe9, 0xf5, 0x74, 0x36, 0x1d, 0x5e, 0xb9, 0xb6, 0xff, 0x27, 0x54, 0x4d,
	0x2a, 0x5d, 0x5f, 0x30, 0x65, 0xee, 0xa5, 0x4d, 0xd1, 0x26, 0xcf, 0x01, 0x16, 0x71, 0xb4, 0x0a,
	0x97, 0x5c, 0x7f, 0xf7, 0xcc, 0x64, 0x05, 0x44, 0xbf, 0x43, 0x98, 0xac, 0x64, 0xb1, 0xc1, 0x16,
	0x05, 0x0d, 0xa5, 0x4d, 0xfd, 0x65, 0x41, 0x2d, 0xd4, 0x87, 0xce, 0x36, 0xe4, 0x47, 0xa8, 0x27,
	0x41, 0x1c, 0xcc, 0x77, 0x22, 0xc2, 0x22, 0x9f, 0x7f, 0x79, 0x68, 0x35, 0xb9, 0x19, 0xed, 0x44,
	0xa4, 0x0f, 0x46, 0x72, 0xb1, 0x0f, 0xd3, 0x82, 0x2d, 0x9a, 0xb9, 0xe4, 0x5b, 0x80, 0xf8, 0x21,
	0xe2, 0x22, 0xc0, 0x3d, 0x99, 0x62, 0x0d, 0x44, 0x86, 0x7a, 0x59, 0x59, 0x33, 0x4b, 0xae, 0x58,
	0xb8, 0x49, 0xef, 0x10, 0x9b, 0xb9, 0x40, 0xc4, 0xef, 0x40, 0xab, 0xa8, 0xc1, 0x79, 0x15, 0xff,
	0x03, 0xde, 0x7e, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x32, 0x23, 0x6f, 0x8c, 0xa4, 0x06, 0x00, 0x00,
}
